#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/Lesson_1_Assignment_Introduction_to_R_Part_1.R /autograder/source/Lesson_1_Assignment_Introduction_to_R_Part_1.R

cd /autograder/source


Rscript grade_one_submission.r 
